// <auto-generated />
using System;
using DeclarationEmployer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeclarationEmployer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260626134923_AddBackupManagement")]
    partial class AddBackupManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeclarationEmployer.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("action");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("details");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("entity_name");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("EntityName");

                    b.HasIndex("OccurredAt");

                    b.ToTable("audit_logs", "audit");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Auth.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("users", "auth");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Backup.BackupEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid>("BackupRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("backup_record_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id");

                    b.HasIndex("BackupRecordId");

                    b.HasIndex("OccurredAt");

                    b.ToTable("backup_events", "backup");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Backup.BackupRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("file_name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Sha256Hash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sha256_hash");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("stored_path");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("backup_records", "backup");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Cabinet.ClientCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Activite")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("activite");

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("adresse");

                    b.Property<string>("Categorie")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("categorie");

                    b.Property<string>("Cle")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("cle");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("CodePostal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code_postal");

                    b.Property<string>("CodeTva")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("code_tva");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Etablissement")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("etablissement");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MatriculeFiscal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("matricule_fiscal");

                    b.Property<string>("RaisonSociale")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("raison_sociale");

                    b.Property<string>("Telephone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telephone");

                    b.Property<string>("Ville")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ville");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("MatriculeFiscal");

                    b.ToTable("clients", "cabinet");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Cabinet.FiscalYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_company_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId", "Year")
                        .IsUnique();

                    b.ToTable("fiscal_years", "cabinet");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.ArchivedDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("ArchivedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("archived_by");

                    b.Property<Guid>("ClientCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_company_id");

                    b.Property<Guid>("DeclarationId")
                        .HasColumnType("uuid")
                        .HasColumnName("declaration_id");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("FiscalYearId")
                        .HasColumnType("uuid")
                        .HasColumnName("fiscal_year_id");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("relative_path");

                    b.Property<string>("Sha256Hash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sha256_hash");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationId");

                    b.HasIndex("DocumentType");

                    b.HasIndex("FiscalYearId");

                    b.HasIndex("ClientCompanyId", "FiscalYearId");

                    b.ToTable("archived_documents", "archive");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.DeclarationAnnex", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnnexCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("annex_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeclarationId")
                        .HasColumnType("uuid")
                        .HasColumnName("declaration_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationId");

                    b.HasIndex("DeclarationId", "AnnexCode");

                    b.ToTable("declaration_annexes", "declaration");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.DeclarationAnomaly", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeclarationId")
                        .HasColumnType("uuid")
                        .HasColumnName("declaration_id");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("entity_name");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resolved");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationId");

                    b.HasIndex("IsResolved");

                    b.HasIndex("Severity");

                    b.ToTable("declaration_anomalies", "declaration");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.DeclarationBeneficiary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeclarationId")
                        .HasColumnType("uuid")
                        .HasColumnName("declaration_id");

                    b.Property<string>("FullNameOrCompanyName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("full_name_or_company_name");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identifier");

                    b.Property<string>("IdentifierType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identifier_type");

                    b.Property<bool>("IsResident")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resident");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationId");

                    b.HasIndex("DeclarationId", "Identifier");

                    b.ToTable("declaration_beneficiaries", "declaration");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.DeclarationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("action");

                    b.Property<Guid>("DeclarationId")
                        .HasColumnType("uuid")
                        .HasColumnName("declaration_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationId");

                    b.HasIndex("OccurredAt");

                    b.ToTable("declaration_events", "declaration");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.DeclarationLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AnnexId")
                        .HasColumnType("uuid")
                        .HasColumnName("annex_id");

                    b.Property<Guid?>("BeneficiaryId")
                        .HasColumnType("uuid")
                        .HasColumnName("beneficiary_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeclarationId")
                        .HasColumnType("uuid")
                        .HasColumnName("declaration_id");

                    b.Property<string>("DocumentReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("document_reference");

                    b.Property<string>("FiscalCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fiscal_category");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("gross_amount");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation_type");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<decimal>("Rate")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("rate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxableAmount")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("taxable_amount");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("WithheldAmount")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("withheld_amount");

                    b.HasKey("Id");

                    b.HasIndex("AnnexId");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("DeclarationId");

                    b.HasIndex("Status");

                    b.ToTable("declaration_lines", "declaration");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.EmployerDeclaration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FiscalYearId")
                        .HasColumnType("uuid")
                        .HasColumnName("fiscal_year_id");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("locked_by");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("FiscalYearId");

                    b.HasIndex("Status");

                    b.HasIndex("ClientCompanyId", "FiscalYearId")
                        .IsUnique();

                    b.ToTable("declarations", "declaration");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.GeneratedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DeclarationId")
                        .HasColumnType("uuid")
                        .HasColumnName("declaration_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_type");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("relative_path");

                    b.Property<string>("Sha256Hash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sha256_hash");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationId");

                    b.HasIndex("FileType");

                    b.ToTable("generated_files", "declaration");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.ValidationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnnexCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("annex_code");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeclarationId")
                        .HasColumnType("uuid")
                        .HasColumnName("declaration_id");

                    b.Property<string>("FieldName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_name");

                    b.Property<string>("Justification")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("justification");

                    b.Property<string>("LineId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("line_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("ValidationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("validation_run_id");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationId");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.HasIndex("ValidationRunId");

                    b.ToTable("validation_results", "validation");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.ValidationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BlockingCount")
                        .HasColumnType("integer")
                        .HasColumnName("blocking_count");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DeclarationId")
                        .HasColumnType("uuid")
                        .HasColumnName("declaration_id");

                    b.Property<int>("InfoCount")
                        .HasColumnType("integer")
                        .HasColumnName("info_count");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("WarningCount")
                        .HasColumnType("integer")
                        .HasColumnName("warning_count");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("validation_runs", "validation");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Fiscal.AnnexDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsOfficialMappingConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_official_mapping_confirmed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("RuleSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_set_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsOfficialMappingConfirmed");

                    b.HasIndex("RuleSetId", "Code")
                        .IsUnique();

                    b.ToTable("annex_definitions", "fiscal");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Fiscal.FiscalFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnnexDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("annex_definition_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("data_type");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("default_value");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_confirmed");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("label");

                    b.Property<int?>("Length")
                        .HasColumnType("integer")
                        .HasColumnName("length");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("PaddingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("padding_type");

                    b.Property<int?>("PositionEnd")
                        .HasColumnType("integer")
                        .HasColumnName("position_end");

                    b.Property<int?>("PositionStart")
                        .HasColumnType("integer")
                        .HasColumnName("position_start");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_reference");

                    b.HasKey("Id");

                    b.HasIndex("IsConfirmed");

                    b.HasIndex("AnnexDefinitionId", "Code")
                        .IsUnique();

                    b.ToTable("field_definitions", "fiscal");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Fiscal.FiscalRateDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_confirmed");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("label");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<decimal>("Rate")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("rate");

                    b.Property<Guid>("RuleSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_set_id");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_reference");

                    b.HasKey("Id");

                    b.HasIndex("IsConfirmed");

                    b.HasIndex("RuleSetId", "Code")
                        .IsUnique();

                    b.ToTable("rate_definitions", "fiscal");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Fiscal.FiscalRuleSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_reference");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Year", "Code")
                        .IsUnique();

                    b.ToTable("rule_sets", "fiscal");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Backup.BackupEvent", b =>
                {
                    b.HasOne("DeclarationEmployer.Domain.Backup.BackupRecord", "BackupRecord")
                        .WithMany("Events")
                        .HasForeignKey("BackupRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackupRecord");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Cabinet.FiscalYear", b =>
                {
                    b.HasOne("DeclarationEmployer.Domain.Cabinet.ClientCompany", "ClientCompany")
                        .WithMany()
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.ArchivedDocument", b =>
                {
                    b.HasOne("DeclarationEmployer.Domain.Cabinet.ClientCompany", "ClientCompany")
                        .WithMany()
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeclarationEmployer.Domain.Declarations.EmployerDeclaration", "Declaration")
                        .WithMany("ArchivedDocuments")
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeclarationEmployer.Domain.Cabinet.FiscalYear", "FiscalYear")
                        .WithMany()
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientCompany");

                    b.Navigation("Declaration");

                    b.Navigation("FiscalYear");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.DeclarationAnnex", b =>
                {
                    b.HasOne("DeclarationEmployer.Domain.Declarations.EmployerDeclaration", "Declaration")
                        .WithMany("Annexes")
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaration");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.DeclarationAnomaly", b =>
                {
                    b.HasOne("DeclarationEmployer.Domain.Declarations.EmployerDeclaration", "Declaration")
                        .WithMany("Anomalies")
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaration");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.DeclarationBeneficiary", b =>
                {
                    b.HasOne("DeclarationEmployer.Domain.Declarations.EmployerDeclaration", "Declaration")
                        .WithMany("Beneficiaries")
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaration");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.DeclarationEvent", b =>
                {
                    b.HasOne("DeclarationEmployer.Domain.Declarations.EmployerDeclaration", "Declaration")
                        .WithMany()
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaration");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.DeclarationLine", b =>
                {
                    b.HasOne("DeclarationEmployer.Domain.Declarations.DeclarationAnnex", "Annex")
                        .WithMany()
                        .HasForeignKey("AnnexId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeclarationEmployer.Domain.Declarations.DeclarationBeneficiary", "Beneficiary")
                        .WithMany()
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeclarationEmployer.Domain.Declarations.EmployerDeclaration", "Declaration")
                        .WithMany("Lines")
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annex");

                    b.Navigation("Beneficiary");

                    b.Navigation("Declaration");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.EmployerDeclaration", b =>
                {
                    b.HasOne("DeclarationEmployer.Domain.Cabinet.ClientCompany", "ClientCompany")
                        .WithMany()
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeclarationEmployer.Domain.Cabinet.FiscalYear", "FiscalYear")
                        .WithMany()
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientCompany");

                    b.Navigation("FiscalYear");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.GeneratedFile", b =>
                {
                    b.HasOne("DeclarationEmployer.Domain.Declarations.EmployerDeclaration", "Declaration")
                        .WithMany("GeneratedFiles")
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaration");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.ValidationResult", b =>
                {
                    b.HasOne("DeclarationEmployer.Domain.Declarations.EmployerDeclaration", "Declaration")
                        .WithMany()
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeclarationEmployer.Domain.Declarations.ValidationRun", "ValidationRun")
                        .WithMany("Results")
                        .HasForeignKey("ValidationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaration");

                    b.Navigation("ValidationRun");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.ValidationRun", b =>
                {
                    b.HasOne("DeclarationEmployer.Domain.Declarations.EmployerDeclaration", "Declaration")
                        .WithMany()
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaration");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Fiscal.AnnexDefinition", b =>
                {
                    b.HasOne("DeclarationEmployer.Domain.Fiscal.FiscalRuleSet", "RuleSet")
                        .WithMany("Annexes")
                        .HasForeignKey("RuleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuleSet");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Fiscal.FiscalFieldDefinition", b =>
                {
                    b.HasOne("DeclarationEmployer.Domain.Fiscal.AnnexDefinition", "AnnexDefinition")
                        .WithMany("Fields")
                        .HasForeignKey("AnnexDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnnexDefinition");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Fiscal.FiscalRateDefinition", b =>
                {
                    b.HasOne("DeclarationEmployer.Domain.Fiscal.FiscalRuleSet", "RuleSet")
                        .WithMany("Rates")
                        .HasForeignKey("RuleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuleSet");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Backup.BackupRecord", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.EmployerDeclaration", b =>
                {
                    b.Navigation("Annexes");

                    b.Navigation("Anomalies");

                    b.Navigation("ArchivedDocuments");

                    b.Navigation("Beneficiaries");

                    b.Navigation("GeneratedFiles");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Declarations.ValidationRun", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Fiscal.AnnexDefinition", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("DeclarationEmployer.Domain.Fiscal.FiscalRuleSet", b =>
                {
                    b.Navigation("Annexes");

                    b.Navigation("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
